/**@desc: Language for script*/
var LAG_CON_HW = "华为";
var LAG_CON_THAN_4 = "不能超过4款产品";
var LAG_CON_ENTER_EMAIL_ADDRESS = "请输入电子邮箱地址.";
var LAG_CON_LENGTH_30 =  "输入长度不能超过30";
var LAG_CON_EMAIL_FORMAT_INCORRECT = "电子邮箱格式错误";
var LAG_CON_LENGTH_90 = "输入的关键字数不能超过90";
var LAG_CON_LENGTH_2 = "至少输入2个关键字";
var LAG_CON_MORE_WORDS = "请输入更多";
var LAG_CON_ENTER_SEARCH_TERM = "请输入搜索关键字";

var LAG_CON_SELECT_PRODUCT = "选择产品型号";
var LAG_CON_NO_RESULTS = "抱歉，未找到合适结果。";
var LAG_CON_VIEW_NOW = "立即查看";
var LAG_CON_SUPPORT = "服务与支持";
var LAG_CON_MANUALS = "产品手册";
var LAG_CON_HW_BG = "华为手机官网";
var LAG_CON_DOWNLOAD_NOW =  "立即下载";
var LAG_CON_DOWNLOADS = "软件下载"; 
var LAG_CON_NO_INFOMATION = "NO INFORMATION"; 
var LAG_CON_ERROR = "错误"; 
var LAG_CON_SELECT_COUNTRY = "选择国家"; 
var LAG_CON_SELECT_CITY = "选择城市"; 
var LAG_CON_NO_DATA = "无数据";
var LAG_CON_SUBSCRIBE = ""; 
var LAG_CON_UNSUBSCRIBE = ""; 
var LAG_CON_PAGE_UNAVAILABLE = ""; 
var LAG_CON_SELECT_CATEGORY = "选择类别"; 
var LAG_CON_SEND_EMAIL_SUCC = "电子邮件发送成功"; 
var LAG_CON_SIMULATOR = "产品模拟器"; 
var LAG_CON_SEND_EMAIL_FAIL = "电子邮件发送失败";
var LAG_CON_WRITE_FEEDBACK_CONTENT = "Please write feedback content";
var LAG_CON_WRITE_NAME = "请输入姓名";
var LAG_CON_WRITE_EMAIL = "请输入正确的电子邮件";
var LAG_CON_WRITE_VALIDATECODE = "请输入正确的验证码";
var LAG_CON_VIEWS = " 次";
var LAG_CON_MORE = "更多";
var LAG_CON_ENTER_COMMENTS = "评论不能为空";
var LAG_CON_MOST_1000 = "最多输入300字";
var LAG_CON_PLEASE_SELECT_PORDUCT = "请选择一款产品";
var LAG_CON_ENTER_CORPORATION_NAME ="";
var LAG_CON_ENTER_PERSON_CONTACT  = "" ;
var LAG_CON_ENTER_PHONE_NUMBER = "";
var LAG_CON_ENTER_FOUNDING_TIME = "";
var LAG_CON_ENTER_COOPERATION_ORIENTATION = "";
var LAG_CON_ENTER_MAINSTREAM_PRODUCTS = "";
var LAG_CON_SELECT_CORPORATION_NATURE = "";
var LAG_CON_ENTER_REGISTERED_CAPITAL = "";
var LAG_CON_ENTER_STAFF_SIZE = "";
var LAG_CON_ENTER_A_PERSON_CONTACT = "";
var LAG_CON_ENTER_ASSETS_SIZE = "";
var LAG_CON_ENTER_FINANCIAL_POSITION = "";
var LAG_CON_ENTER_ANNUAL_REVENUE = "";
var LAG_CON_ENTER_MAJOR_CUSTOMERS = "";
var LAG_CON_ENTER_PRODUCTION_AND_DELIVERY = "";
var LAG_CON_ENTER_DEVELOPMENT_PROSPECTS = "";
var LAG_CON_PLE_SEL_CATEGORY = "请选择主题和类别";
var LAG_CON_ENTER_QUESTION ="请输入反馈信息";
var LAG_CON_ENTER_AN_EMAIL_ADDRESS ="请输入电子邮箱";
var LAG_CON_ENTER_MODEL ="请输入产品型号";
var LAG_CON_ENTER_PURCHASE_DATE="Please enter a purchase date.";
var LAG_CON_DATE_FORMAT_INCORRECT ="请输入正确的购买时间，格式:2013-01-01";
var LAG_CON_VALIDATE_CODE_ERROR ="验证码错误";
var LAG_CON_ENTER_MORE_TERM = "至少输入2个关键字";
var LAG_CON_WEBSITE = "";
var LAG_CON_SELECT_TYPE = "选择产品类别";
var LAG_CON_SUBMIT_SUCC = "提交成功";
var LAG_CON_CAN_NOT_SUB = "提交失败";
var LAG_CON_DATE_LESS_THAN_TODAY = "Purchase Date must less than today";
var LAG_CON_COMPARE = "产品对比";
var LAG_CON_REMOVE  ="删除";
var LAG_CON_PLE_SELECT_CITY  ="请选择城市";
var LAG_CON_VCODE = "验证码"
var LAG_CON_DATA_FORMAT = "格式：2013-01-01"
var LAG_CON_INTER_Q = "请输入问题"
var LAG_CON_PIC_CONTENT = "图文";
var LAG_CON_VIDEO = "视频";
var LAG_CON_SEARCH_RESULT = "搜索结果";
var LAG_CON_ALL2 = "全部";
var LAG_CON_SENDSUCC = "发送短信成功";
var LAG_CON_SENDUNSUCC = "发送短信失败";
var LAG_CON_CANCELSUCC = "取消成功";
var LAG_CON_ALREADYRES = "已预约";
var LAG_CON_ALREADYCANCEL = "已取消";
var LAG_CON_ALREADYHERE = "已到店";
var LAG_CON_ALREADYOK = "已完成";
var LAG_CON_REPAIR = "故障维修";
var LAG_CON_CHECKMP = "换机检查";
var LAG_CON_DOSUCESS = "操作成功";
var LAG_CON_DOUNSUCESS = "操作失败";
var LAG_CON_SEARCHERROR = "查询失败";
var LAG_CON_CUCARD = "会员铜卡等级";
var LAG_CON_AGCARD = "会员银卡等级";
var LAG_CON_AUCARD = "会员金卡等级";
var LAG_CON_MEMBERLV = "会员等级";
var LAG_CON_NOMEMBER = "不存在的会员号";  
var LAG_CON_READ_MORE = "了解更多";
var LAG_CON_AWARD_COUNTRY = "Award Country";
var LAG_CON_SEARCH_ABOUT_1 = "找到";
var LAG_CON_SEARCH_ABOUT_2 = "的结果";
var LAG_CON_SEARCH_ABOUT_3 = "条关于";
var LAG_CON_APPLY_READY = "已申请"
var LAG_CON_SHOP_CONFIRM = "已到店确认"
var LAG_CON_FIXED_DONE = "已完成维修"
var LAG_CON_POSTING = "已邮寄发货"
var LAG_CON_RECIEVED = "已取机"
var LAG_CON_APPLY_BACK = "预约单已撤销"
var LAG_CON_TIME_OUT = "预约单已过期作废"
var LAG_CON_SUPPORT_CARRY_ERROR = "无";
var LAG_CON_SUPPORT_CARRY_SECCUS = "个月";
function setSearchKeys(key){
  return '关于"' + key + '"的搜索结果'
}
function setsetSearchResults(rows,key){
  return '找到关于"' + key + '"的结果'+rows+'条'
}
